/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Matriculados;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.OrdenacaoCursoEnfaseNome;
import persistencia.OrdenacaoCursoNome;
import persistencia.OrdenacaoEnfaseCursoNome;
import persistencia.OrdenacaoEnfaseNome;
import persistencia.OrdenacaoPorNome;
import persistencia.OrdenacaoPorSobrenome;
import persistencia.OrdenacaoSituacaoCursoNome;
import persistencia.OrdenacaoSituacaoNome;

/**
 *
 * @author edivan
 */
public class Aplicacao extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public Aplicacao() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMatricula = new javax.swing.JTable();
        btnNome = new javax.swing.JButton();
        btnSobreNome = new javax.swing.JButton();
        btnCursoNome = new javax.swing.JButton();
        btnEnfaseNome = new javax.swing.JButton();
        btnSituacaoNome = new javax.swing.JButton();
        btnCursoEnfaseNome = new javax.swing.JButton();
        btnEnfaseCursoNome = new javax.swing.JButton();
        btnSituacaoCursoNome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CURSO", "SITUAÇÃO", "ENSAFE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMatricula);

        btnNome.setText("Nome");
        btnNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomeActionPerformed(evt);
            }
        });

        btnSobreNome.setText("Sobre Nome");
        btnSobreNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreNomeActionPerformed(evt);
            }
        });

        btnCursoNome.setText("Curso - Nome");
        btnCursoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoNomeActionPerformed(evt);
            }
        });

        btnEnfaseNome.setText("Enfase - Nome");
        btnEnfaseNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnfaseNomeActionPerformed(evt);
            }
        });

        btnSituacaoNome.setText("Situação - Nome");
        btnSituacaoNome.setPreferredSize(new java.awt.Dimension(147, 31));
        btnSituacaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSituacaoNomeActionPerformed(evt);
            }
        });

        btnCursoEnfaseNome.setText("Curso - Enfase - Nome");
        btnCursoEnfaseNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoEnfaseNomeActionPerformed(evt);
            }
        });

        btnEnfaseCursoNome.setText("Enfase - Curso - Nome");
        btnEnfaseCursoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnfaseCursoNomeActionPerformed(evt);
            }
        });

        btnSituacaoCursoNome.setText("Situação - Curso - Nome");
        btnSituacaoCursoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSituacaoCursoNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 320, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCursoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEnfaseNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSituacaoNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCursoEnfaseNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnfaseCursoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSituacaoCursoNome))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnCursoNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCursoEnfaseNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNome)
                    .addComponent(btnEnfaseNome)
                    .addComponent(btnEnfaseCursoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSituacaoCursoNome)
                    .addComponent(btnSituacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSobreNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void imprimirGrid(ArrayList<Matriculados> dados) {
        try {
            DefaultTableModel model = (DefaultTableModel) tableMatricula.getModel();
            model.setNumRows(0);
            int pos = 0;
            while (pos < dados.size()) {
                String[] linha = new String[4];
                Matriculados obj = dados.get(pos);
                linha[0] = obj.getNome();
                linha[1] = obj.getCurso();
                linha[2] = obj.getSituacao();
                linha[3] = obj.getEnfase();
                model.addRow(linha);
                pos++;
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }
    private void btnNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomeActionPerformed
        try {
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenacaoPorNome objeto = new OrdenacaoPorNome(nome);
            imprimirGrid(objeto.listagemDeMatriculados());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnNomeActionPerformed

    private void btnSobreNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreNomeActionPerformed
        try {
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenacaoPorSobrenome objeto = new OrdenacaoPorSobrenome(nome);
            imprimirGrid(objeto.listagemDeMatriculados());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_btnSobreNomeActionPerformed

    private void btnCursoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoNomeActionPerformed
        try {
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenacaoCursoNome objeto = new OrdenacaoCursoNome(nome);
            imprimirGrid(objeto.listagemDeMatriculados());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_btnCursoNomeActionPerformed

    private void btnEnfaseNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnfaseNomeActionPerformed
        try {
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenacaoEnfaseNome objeto = new OrdenacaoEnfaseNome(nome);
            imprimirGrid(objeto.listagemDeMatriculados());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_btnEnfaseNomeActionPerformed

    private void btnSituacaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSituacaoNomeActionPerformed
        try {
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenacaoSituacaoNome objeto = new OrdenacaoSituacaoNome(nome);
            imprimirGrid(objeto.listagemDeMatriculados());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_btnSituacaoNomeActionPerformed

    private void btnCursoEnfaseNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoEnfaseNomeActionPerformed
        try {
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenacaoCursoEnfaseNome objeto = new OrdenacaoCursoEnfaseNome(nome);
            imprimirGrid(objeto.listagemDeMatriculados());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_btnCursoEnfaseNomeActionPerformed

    private void btnEnfaseCursoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnfaseCursoNomeActionPerformed
        try {
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenacaoEnfaseCursoNome objeto = new OrdenacaoEnfaseCursoNome(nome);
            imprimirGrid(objeto.listagemDeMatriculados());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_btnEnfaseCursoNomeActionPerformed

    private void btnSituacaoCursoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSituacaoCursoNomeActionPerformed
        try {
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenacaoSituacaoCursoNome objeto = new OrdenacaoSituacaoCursoNome(nome);
            imprimirGrid(objeto.listagemDeMatriculados());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_btnSituacaoCursoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursoEnfaseNome;
    private javax.swing.JButton btnCursoNome;
    private javax.swing.JButton btnEnfaseCursoNome;
    private javax.swing.JButton btnEnfaseNome;
    private javax.swing.JButton btnNome;
    private javax.swing.JButton btnSituacaoCursoNome;
    private javax.swing.JButton btnSituacaoNome;
    private javax.swing.JButton btnSobreNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMatricula;
    // End of variables declaration//GEN-END:variables
}
