package view;

import bll.FabricanteBll;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Fabricantes;

/**
 *
 * @author edivan
 */
public class TelaFabricantes extends javax.swing.JInternalFrame {

    Fabricantes fab = new Fabricantes();
    FabricanteBll fabBll = new FabricanteBll();

    /**
     * Creates new form Telateste
     */
    public TelaFabricantes() throws Exception {
        initComponents();
        //consultarFabricantes(fabBll.consultarFabricantes());

    }

    private void consultarFabricantes(List<Fabricantes> lista) throws Exception {
        DefaultTableModel modelo = (DefaultTableModel) tableFabricante.getModel();
        modelo.setNumRows(0);
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[2];
            Fabricantes aux = lista.get(pos);
            linha[0] = aux.getIden() + "";
            linha[1] = aux.getNome() + "";
            modelo.addRow(linha);

        }
    }

    private void limpaCampos() {
        txtFabId.setText("");
        txtFabNome.setText("");
    }

    private void preencheCampos(int id) throws Exception {

        try {

            if (id > 0) {

                fab = fabBll.consultarFabricantesPorId(id);
                txtFabId.setText(id + "");
                txtFabNome.setText(fab.getNome());
                btnFabSalvar.setLabel("Editar");
            } else {
                btnFabSalvar.setLabel("Salvar");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFabNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFabricante = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFabId = new javax.swing.JTextField();
        btnFabSalvar = new javax.swing.JButton();
        btnFabExcluir = new javax.swing.JButton();
        btnFabConsultar = new javax.swing.JButton();
        btnFabNovo = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela de Cadastro Fabricantes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setVisible(true);

        jLabel1.setText("Nome");

        tableFabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFabricanteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFabricante);
        if (tableFabricante.getColumnModel().getColumnCount() > 0) {
            tableFabricante.getColumnModel().getColumn(0).setMinWidth(50);
            tableFabricante.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableFabricante.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel2.setText("ID");

        btnFabSalvar.setText("Salvar");
        btnFabSalvar.setPreferredSize(new java.awt.Dimension(100, 45));
        btnFabSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabSalvarActionPerformed(evt);
            }
        });

        btnFabExcluir.setText("Excluir");
        btnFabExcluir.setPreferredSize(new java.awt.Dimension(100, 45));
        btnFabExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabExcluirActionPerformed(evt);
            }
        });

        btnFabConsultar.setText("Consultar");
        btnFabConsultar.setPreferredSize(new java.awt.Dimension(100, 45));
        btnFabConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabConsultarActionPerformed(evt);
            }
        });

        btnFabNovo.setText("Novo");
        btnFabNovo.setPreferredSize(new java.awt.Dimension(100, 45));
        btnFabNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnFabSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFabExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFabConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFabNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFabId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFabNome))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFabId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFabNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFabSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFabExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFabConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFabNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setBounds(0, 0, 562, 344);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFabSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabSalvarActionPerformed
        try {
            fab.setNome(txtFabNome.getText());
            if (btnFabSalvar.getLabel().equals("Salvar")) {
                fabBll.adicionarFabricante(fab);

            } else {
                fabBll.alterarFabricante(fab);

            }
            consultarFabricantes(fabBll.consultarFabricantes());
            limpaCampos();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnFabSalvarActionPerformed

    private void btnFabExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabExcluirActionPerformed
        try {
            fabBll.removerFabricante(fabBll.consultarFabricantesPorId(fab.getIden()));
            limpaCampos();
            consultarFabricantes(fabBll.consultarFabricantes());
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btnFabExcluirActionPerformed

    private void btnFabConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabConsultarActionPerformed
        try {
            consultarFabricantes(fabBll.consultarFabricantes());

        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btnFabConsultarActionPerformed

    private void btnFabNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabNovoActionPerformed
        limpaCampos();
        txtFabNome.requestFocus();
        btnFabSalvar.setLabel("Salvar");
        
    }//GEN-LAST:event_btnFabNovoActionPerformed

    private void tableFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFabricanteMouseClicked
        int linha = tableFabricante.getSelectedRow();
        Integer codigo = Integer.parseInt(tableFabricante.getValueAt(linha, 0).toString());
        try {
            preencheCampos((int) codigo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher campo");
        }

    }//GEN-LAST:event_tableFabricanteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFabConsultar;
    private javax.swing.JButton btnFabExcluir;
    private javax.swing.JButton btnFabNovo;
    private javax.swing.JButton btnFabSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFabricante;
    private javax.swing.JTextField txtFabId;
    private javax.swing.JTextField txtFabNome;
    // End of variables declaration//GEN-END:variables
}
