
package view;

import bll.Tipo_MiniaturaBll;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Tipo_Miniaturas;

/**
 *
 * @author edivan
 */
public class TelaTipo_Miniatura extends javax.swing.JInternalFrame {

    Tipo_Miniaturas tMiniatura = new Tipo_Miniaturas();
    Tipo_MiniaturaBll tMiniaturasBll = new Tipo_MiniaturaBll();
    
        
    /**
     * Creates new form TelaTipo_Miniatura
     */
    public TelaTipo_Miniatura() {
        initComponents();
    }
    
    private void consultarTipo_Miniaturas(List<Tipo_Miniaturas> lista) throws Exception {
        DefaultTableModel modelo = (DefaultTableModel) tableTipoMiniatura.getModel();
        modelo.setNumRows(0);
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[2];
            Tipo_Miniaturas aux = lista.get(pos);
            linha[0] = aux.getIden() + "";
            linha[1] = aux.getTipo()+ "";
            modelo.addRow(linha);

        }
    }
    
    private void limpaCampos() {
        txtTipId.setText("");
        txtTipTipo.setText("");
    }

    private void preencheCampos(int id) throws Exception {

        try {
            if (id > 0) {

                tMiniatura = tMiniaturasBll.consultaTipo_MiniaturasPorId(id);
                txtTipId.setText(id + "");
                txtTipTipo.setText(tMiniatura.getTipo());
                btnTipoSalvar.setLabel("Editar");
            } else {
                btnTipoSalvar.setLabel("Salvar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTipId = new javax.swing.JTextField();
        txtTipTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTipoMiniatura = new javax.swing.JTable();
        btnTipoSalvar = new javax.swing.JButton();
        btnTipoExcluir = new javax.swing.JButton();
        btnTipoConsultar = new javax.swing.JButton();
        btnTipoNovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela Tipo de Miniatura");
        setPreferredSize(new java.awt.Dimension(562, 347));

        jLabel1.setText("ID");

        jLabel2.setText("Tipo");

        tableTipoMiniatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTipoMiniatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTipoMiniaturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTipoMiniatura);
        if (tableTipoMiniatura.getColumnModel().getColumnCount() > 0) {
            tableTipoMiniatura.getColumnModel().getColumn(0).setMinWidth(50);
            tableTipoMiniatura.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableTipoMiniatura.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnTipoSalvar.setText("Salvar");
        btnTipoSalvar.setPreferredSize(new java.awt.Dimension(100, 45));
        btnTipoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoSalvarActionPerformed(evt);
            }
        });

        btnTipoExcluir.setText("Excluir");
        btnTipoExcluir.setPreferredSize(new java.awt.Dimension(100, 45));
        btnTipoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoExcluirActionPerformed(evt);
            }
        });

        btnTipoConsultar.setText("Consultar");
        btnTipoConsultar.setPreferredSize(new java.awt.Dimension(100, 45));
        btnTipoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoConsultarActionPerformed(evt);
            }
        });

        btnTipoNovo.setText("Novo");
        btnTipoNovo.setPreferredSize(new java.awt.Dimension(100, 45));
        btnTipoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipTipo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTipId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTipoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTipoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTipoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTipoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTipoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTipoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTipoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTipoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setBounds(0, 0, 562, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTipoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoSalvarActionPerformed
        try {
            tMiniatura.setTipo(txtTipTipo.getText());
            if (btnTipoSalvar.getLabel().equals("Salvar")) {
                tMiniaturasBll.adicionarTipo_Miniatura(tMiniatura);
            } else {
                tMiniaturasBll.alterarTipo_Miniatura(tMiniatura);
            }
            consultarTipo_Miniaturas(tMiniaturasBll.consultarTipo_Miniaturas());
            limpaCampos();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTipoSalvarActionPerformed

    private void btnTipoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoExcluirActionPerformed
        try {
            tMiniaturasBll.removerTipo_Miniatura(tMiniaturasBll.consultaTipo_MiniaturasPorId(tMiniatura.getIden()));
            limpaCampos();
            consultarTipo_Miniaturas(tMiniaturasBll.consultarTipo_Miniaturas());
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btnTipoExcluirActionPerformed

    private void btnTipoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoConsultarActionPerformed
        try {
            consultarTipo_Miniaturas(tMiniaturasBll.consultarTipo_Miniaturas());

        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btnTipoConsultarActionPerformed

    private void btnTipoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoNovoActionPerformed
        limpaCampos();
        txtTipTipo.requestFocus();
        btnTipoSalvar.setLabel("Salvar");
    }//GEN-LAST:event_btnTipoNovoActionPerformed

    private void tableTipoMiniaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTipoMiniaturaMouseClicked
        int linha = tableTipoMiniatura.getSelectedRow();
        Integer codigo = Integer.parseInt(tableTipoMiniatura.getValueAt(linha, 0).toString());
        try {
            preencheCampos((int) codigo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher campo");
        }
    }//GEN-LAST:event_tableTipoMiniaturaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTipoConsultar;
    private javax.swing.JButton btnTipoExcluir;
    private javax.swing.JButton btnTipoNovo;
    private javax.swing.JButton btnTipoSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTipoMiniatura;
    private javax.swing.JTextField txtTipId;
    private javax.swing.JTextField txtTipTipo;
    // End of variables declaration//GEN-END:variables
}
